---
title: "Reading .fit files"
author: "Mike Smith"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_lib}
library(fitFileR)
```

## Example fit files

The package comes with two example fit files, recorded during a ride in early 2017.  They are of the same ride and record the same rider, but the data logging was carried out on two different devices: a Garmin Edge 500 and a TomTom Runner 3.  

```{r data_files}
garmin_file <- system.file("extdata/Garmin.fit", package = "fitFileR")
tomtom_file <- system.file("extdata/TomTom.fit", package = "fitFileR")
```

```{r reading_files}
garmin <- readFitFile(garmin_file)
tomtom <- readFitFile(tomtom_file)
```


# Generating internal lists of data types and messages

```{r, eval = FALSE}
library(openxlsx)
t2 <- read.xlsx('~/projects/fit_files/Profile_gsheets.xlsx', sheet = 2)
rm.idx <- which(is.na(t2[,1]) & is.na(t2[,2]) & is.na(t2[,3]))
t3 <- t2[-rm.idx,1:4]
names(t3) <- c("message_type", "key", "value", "type")
t3[,'type'] <- as.factor(t3[,'type'])

idx <- which(!is.na(t3[,1]))
t3[,1] <- rep(t3[idx,1], 
                diff(c(idx, nrow(t3)+1)))
t3 <- as_data_frame(t3[-which(is.na(t3[,2])),])

message_list <- split(t3[,2:4], t3[[1]])
```

```{r, eval = FALSE}
library(tibble)
t1 <- read.xlsx('~/projects/fit_files/Profile_gsheets.xlsx', sheet = 1)[,c(1,4,3,2)]
t1 <- setNames(t1, c("data_type", "key", "value", "key_type"))
idx <- which(!is.na(t1[,1]))
t1[,1] <- rep(t1[idx,1], 
              diff(c(idx, nrow(t1)+1)))
t1[,4] <- rep(t1[idx,4], 
              diff(c(idx, nrow(t1)+1)))
t1 <- as_data_frame(t1[-which(is.na(t1[,2])),])
fit_data_types <- split(t1[,2:4], t1[[1]])
fit_data_types <- lapply(fit_data_types, FUN = function(x) {
  mutate(x, key = ifelse(grepl('uint32', key_type), 
                         yes = as.numeric(key), 
                         no = as.integer(key))) %>%
    select(-key_type)
})
save(fit_data_types, file = '~/projects/fit_files/fitFileR/data/fit_data_types.rda')
```


